apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: mywebapp
spec:
  selector:
    app: mywebapp
    tier: frontend
  ports:
  - port: 80
    targetPort: <Target Port>
    protocol: TCP
    name: flask
  type: LoadBalancer
