version: '3'

name: nx_101

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-certs/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - ./nginx/nginx-certs/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
    # links:
    #   - my_node_app1
    #   - my_node_app2
    #   - my_node_app3
    depends_on:
      - my_node_app1
      - my_node_app2
      - my_node_app3

  my_node_app1:
    build: ./myapp
    environment:
      - APP_NAME=my_node_app1
    expose:
      - 3000
    # ports:
    #   - "3001:3000"
    volumes:
      - ./myapp:/app
  
  my_node_app2:
    build: ./myapp
    environment:
      - APP_NAME=my_node_app2
    expose:
      - 3000
    # ports:
    #   - "3002:3000"
    volumes:
      - ./myapp:/app
  
  my_node_app3:
    build: ./myapp
    environment:
      - APP_NAME=my_node_app3
    expose:
      - 3000
    # ports:
    #   - "3003:3000"
    volumes:
      - ./myapp:/app      